### ISSUE TITLE
cd /d C:\Users : The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by cardin** [shunsambongi/clink-zoxide#3]
I find that the command `cd /d C:\Users` will give an error `The filename, directory name, or volume label syntax is incorrect.`

However, this command `<space>cd /d C:\Users` works instead.

```cmd
cd /d C:\Users
```
versus
```cmd
 cd /d C:\Users
```

In which case, there needs to be a \<space\> inserted inside the return output of lua function `__zoxide_cd`.

I don't really understand what's going on, but the idea of inserting a \<space\> was inspired by https://github.com/chrisant996/clink/issues/191#issuecomment-960427056

I'm using Clink v1.4.3.67deea on Windows Terminal cmd.

**Comment by cardin** [comment]
> EDIT: Please ignore everything in this issue, including ignoring the stuff after this section.
I've no idea what happened, but after restarting the terminal and my editor several times, the problem went away. Now, I can't reproduce anything of what I'd said earlier as everything seems to be working fine. 🤷I'm terribly sorry for any confusion I might have caused.

-----

>I'm not sure I understand exactly what the difference is between the two commands you shared..

Apologies, GitHub ate away my space character. I'd modified my initial comment to add the space character back in.

Basically it has to do with the `cd` command being incorrect (for some reason). Both snippets below are run in cmd.
```cmd
$ cd /d C:\Users
The filename, directory name, or volume label syntax is incorrect.
```

But if I insert a "space" in front of `cd`, it works:
```cmd
$  cd /d C:\Users
```

I'm not entirely sure what's going on regarding the need for that "space", which is why I'm a little hesitant to make a PR.

**Comment by cardin** [comment]
Okay the problem appears sporadically. The main issue it caused is basically whether `cd` needs a space prefix or not.

I have several things running in cmd: `clink`, `starship`, `fnm` and `clink-zoxide`, so together they may have had some interactions that affected `cd`.

Not having much knowledge in clink I'm not sure how to proceed. >_< For now I'll just move `zoxide.lua` outside of clink's script dir.

**Comment by phanirithvij** [comment]
I had this same issue, I found that I had defined an alias for `cd` as `cd=chdir /d $*` in a `user_aliases.cmd` file. (I use cmder installed clink)
Had to remove it to fix this. Not sure if this applies to you @cardin.

**Comment by cardin** [comment]
I found the cause: a NodeJS env manager FNM (https://github.com/Schniz/fnm) was modifying `cd` as well.

I had to remove `--use-on-cd` portion of the FNM command `FOR /f "tokens=*" %i IN ('fnm env --use-on-cd') DO CALL %i`. Thankfully I wasn't relying on that particular feature of FNM so I'm fine with disabling it.

**Comment by chrisant996** [comment]
> ```batchfile
> $ cd /d C:\Users
> The filename, directory name, or volume label syntax is incorrect.
> ```

@cardin I just found out last night, that error happens when Command Extensions are disabled in CMD, by the `/e:off` flag or by the `EnableExtensions` regkey value (see [cmd](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cmd) docs for details).

The `cd /d` command only works when Command Extensions are enabled.

**Comment by cardin** [comment]
@chrisant996 Thanks for looking into the issue!

I haven’t had `cd` issues after I removed FNM so perhaps FNM was doing that Command Extensions modification to CMD.
