### ISSUE TITLE
Not working properly for me

### ISSUE THREAD

**Issue by eggbean** [shunsambongi/clink-zoxide#5]
Hi, I am glad to find this, as I use zoxide on Linux and even with clink, cmd.exe is very hard to navigate quickly.

I have added the `zoxide.lua` file into a `%CLINK_PATH%` (set in `clink_start.cmd`) and I can see this at the end of the output of `click set`:

    zoxide.cmd                        z
    zoxide.hook                       pwd
    zoxide.no_aliases                 False

The `z` command is not working at all:

    C:\Users\jason\winfiles\Settings>z vimfiles
    ** Options error: unable to interpret options
    Use --help to see possible options

`zi` has started to populate, but not for every directory I have visited for some reason - I think it misses variables like `cd %USERPROFILE%`, which is exactly what I want to use zoxide to make it easier. How can I make it remember my home location?

Selecting a line in `zi`'s `fzf` list leads to the same error for `z`.

What am I doing wrong? Cheers.

**Comment by chrisant996** [comment]
I searched in github.com for the text "Options error: unable to interpret options".

It comes from the [cd-deluxe](https://github.com/eggbean/cd-deluxe) repo.

zoxide expects `cd` to be the CMD `cd` command, but you have an alternative program cd-deluxe that intercepts the `cd` command, which causes the errors because cd-deluxe's options are incompatible with the CMD `cd` command.

**Comment by eggbean** [comment]
Thanks for spotting this - it would have remained a mystery otherwise. 

I have a `doskey cd=cdd.cmd $*` in my `clink_start.cmd` to use cd-deluxe. I've been using cd-deluxe on Windows and Linux for 13 years, so I would rather lose zoxide (on Windows) rather than it, if I can't get them both to work together.

Isn't this something that should really be fixed in zoxide? I would think it should be calling `cd` like `command cd $@` would in bash.

**Comment by chrisant996** [comment]
Ah, **it is a bug in zoxide**:

It is building strings like `'cd -'`.
https://github.com/shunsambongi/clink-zoxide/blob/c9e31f8832b4357891b540d0874695616a2a85aa/zoxide.lua#L24

But that allows doskey macros to intercept the `cd` command.

It needs to build strings like `' cd -'` instead -- notice the leading space, which disables doskey macro expansion.

**Comment by eggbean** [comment]
Oh that's good, it's not actually a bug in zoxide itself, but this clink helper script, so it's much easier to resolve. I'll make a PR soon.

**Comment by eggbean** [comment]
It looks like somebody else already tried to. https://github.com/shunsambongi/clink-zoxide/pull/4

@shunsambongi Could you fix this?

**Comment by shunsambongi** [comment]
@eggbean Sure the fix sounds easy enough. I just pushed to the `fix-cd-command` branch. Can you test it and let me know if it works? I don't have a Windows computer to test, so I'd appreciate if you could try it and report back here.

**Comment by eggbean** [comment]
@shunsambongi Sorry, it seems that I forgot to reply to you, but yes, it works with the two additional spaces. I have zoxide working fine. Thanks, should be merged I think.
