### ISSUE TITLE
The syntax of the command is incorrect

### ISSUE THREAD

**Issue by trungklam** [shunsambongi/clink-zoxide#8]
I got the issue "the syntax of the command is incorrect"

My current setup:
+ Zoxide latest version
+ Cmder with clink latest version
+ zoxide.lua put in `cmder\vendor\clink` and I already checked it was loaded via `clink info` and clink log

![image](https://github.com/shunsambongi/clink-zoxide/assets/17236895/de122937-9db6-4765-a749-230440d7d1ad)

![image](https://github.com/shunsambongi/clink-zoxide/assets/17236895/2df0d6d6-660b-4745-8353-a2666f503446)

I'm not sure am I missing any steps. Appreciate any help ! Thank you

**Comment by JakeHandsome** [comment]
Hey I ran into a similar issue. 

I already had a setup  for `doskey cd=cd /D $*` which I needed to remove because zoxide already calls `cd /d <dir>`

Otherwise it will end up doing `cd /d /d <dir>` which prints "the syntax of the command is incorrect"

**Comment by trungklam** [comment]
> Hey I ran into a similar issue.
> 
> I already had a setup for `doskey cd=cd /D $*` which I needed to remove because zoxide already calls `cd /d <dir>`
> 
> Otherwise it will end up doing `cd /d /d <dir>` which prints "the syntax of the command is incorrect"

Thank you ! This actually the issue !
I didnt know that I somehow set an alias "cd=cd /d $*". After removing it, zoxide works properly 😄
